### ISSUE TITLE
Static Assets Database

### ISSUE THREAD

**Issue by RamiroHR** [RamiroHR/TradingBotApp_mlops#1]
@ArnoMac @Subrat75 (I created this issue so we can test how to interact via GitHub. Issues allow us to discusse about a single topic and keep track on the progress being made)

I think we should define what it will be the static database. If I understood well this will be the data used to train and fine tune the models.

Thanks to the Binance notebook @ArnoMac provided we should be able to download this data for a few assets, BTCUSDT for example. These are TimeSeries, so I guess that we can set a limit date (12/12/2023 ?) and say that data before that will be used for training/validation and data after will be considered as "new data" (for retraining or monitoring in the scope of our mlops project). Of course in reality for training our models we would like to have the most up to date data.

Once a limit date is fixed, we should transform the notebook into a make_assets_data.py script, within the "src/data/" directory, containing functions that when called, download the historic price data for a given asset (until the limit date) and store it into the "./data/raw" directory.

**Comment by ArnoMac** [comment]
Not sure to fully understand why we should set a limit date ?

In my mind, the idea was to have the following database:
- raw data from binance
- processed data ; ready for modeling

For the training/validation, I think we can use the complete historical data and split the data with something like TimeSeriesSplit (from sklearn.model_selection); resulting in a set of data for training and a set for validation.

**Comment by RamiroHR** [comment]
We are not forced to set a "limit date" in advance per se. I think what you propose works fine too... What I meant is that we should all have ( in our github repos ) the same dataset for the training phase (in this case the limit date will be the last date of this dataset). 

The model will be trained a first time once, and then the saved model will be called by the API multiple times to do predictions. Even if there is new data available to download after a couple days, the training set should not change every time we connect to the github. We will probably monitor the performance on this model, predictions after predictions, on new data but this new data will not be added rigth away to the csv file containing the training dataset. 

Only when we detect a drop in the model performance the training dataset will be updated with the binance API and the model retrained again.

For the moment, It is good to have the  make_dataset.py script that creates the **raw data** dataset at the correct location
