### ISSUE TITLE
Update README with basic instructions

### ISSUE THREAD

**Issue by RamiroHR** [RamiroHR/TradingBotApp_mlops#8]
Arnaud Machefel
 [7:12 PM](https://dst-oct23.slack.com/archives/C06BH3R1RK2/p1708107133837319)

Dans l'ordre, il faut faire :
/price_hist pour récupérer les prix
/update_model_params pour créer les paramètres d'un modèle
/train_model pour entrainer le modèle à utiliser en prod
/prediction pour avoir la prédiction actuelle

**Comment by ArnoMac** [comment]
I just added some clarification in the branch update_readme
