### ISSUE TITLE
Assess_performance endpoint bug

### ISSUE THREAD

**Issue by RamiroHR** [RamiroHR/TradingBotApp_mlops#9]
Bug when trying to assess the performance over data "BTCUSDT-1d". 
It seems that there are not enough data points to make a cross-validation with 10 splits.

**Curl response**
Error Code 500: internal Server error.

**uvicorn terminal**
ValueError: Too many splits=10 for number of samples=2250 with test_size=1000 and gap=0.

Endpoint works fine with "BTCUSDT-4h"

**Comment by ArnoMac** [comment]
Thanks Ramiro.
The branch "update_model_functions" should fix this issue.
